config/routes.rb
Ethanbook::Application.routes.draw do
  get "profiles/show"
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed
  
  devise_scope :user do
    get 'register', to: 'users/registrations#new', as: :register
    get 'sign-in', to: 'devise/sessions#new', as: :sign_in
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end
  
  
  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as: :profile

end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user
  
  validates :content, presence: true, 
                      length: { minimum: 2 }
    
  validates :user_id, presence: true    

                
              
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   has_many :statuses
   has_many :user_friendships
   has_many :friends, through: :user_friendships

   def full_name
     first_name + " " + last_name
   end   
   
   def gravatar_url
      stripped_email = email.strip
      downcased_email = stripped_email.downcase
      hash = Digest::MD5.hexdigest(downcased_email)

      "http://gravatar.com/avatar/#{hash}"
   end
   
   validates :first_name, presence: true
   validates :last_name, presence: true
   validates :profile_name, presence: true,
                            uniqueness: true,
                            
                            format: {
                              with: /^[a-zA-Z0-9-]+$/,
                              :multiline => true,
                              message: 'Must be formatted correctly.'
                            }
   
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  

end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	
  def show
    @user = User.find_by_profile_name(params[:id])
    if @user
      @statuses = @user.statuses
      render action: :show
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  


  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json

  def update
    @status = current_user.statuses.find(params[:id])

    if params[:status] && params[:status].has_key?(:user_id)
      params[:status].delete(:user_id) 
    end
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :content, :user_id) if params[:status]
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def sign_up_params
     params.require(:user).permit(:first_name, :last_name, :profile_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def flash_class(type)
    case type
    when :alert
      "alert-danger"
    when :notice
      "alert-success"
    else 
      "alert-info"
    end
  end  
   
  
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ethanbook</title>
  <link data-turbolinks-track="true" href="/assets/application.css?body=1" media="all" rel="stylesheet" />
<link data-turbolinks-track="true" href="/assets/bootstrap-theme.css?body=1" media="all" rel="stylesheet" />
<link data-turbolinks-track="true" href="/assets/bootstrap-theme.min.css?body=1" media="all" rel="stylesheet" />
<link data-turbolinks-track="true" href="/assets/bootstrap.css?body=1" media="all" rel="stylesheet" />
<link data-turbolinks-track="true" href="/assets/bootstrap.min.css?body=1" media="all" rel="stylesheet" />
<link data-turbolinks-track="true" href="/assets/profiles.css?body=1" media="all" rel="stylesheet" />
<link data-turbolinks-track="true" href="/assets/scaffolds.css?body=1" media="all" rel="stylesheet" />
<link data-turbolinks-track="true" href="/assets/statuses.css?body=1" media="all" rel="stylesheet" />
  <script data-turbolinks-track="true" src="/assets/jquery.js?body=1"></script>
<script data-turbolinks-track="true" src="/assets/jquery_ujs.js?body=1"></script>

<script data-turbolinks-track="true" src="/assets/bootstrap.js?body=1"></script>
<script data-turbolinks-track="true" src="/assets/bootstrap.min.js?body=1"></script>
<script data-turbolinks-track="true" src="/assets/profiles.js?body=1"></script>
<script data-turbolinks-track="true" src="/assets/statuses.js?body=1"></script>
<script data-turbolinks-track="true" src="/assets/application.js?body=1"></script>
  <meta name="google-site-verification" content="kKTHhNjapuFDmwDtfeDD1FP0Qh7ngw3KXyerKBGJW_I" />
  <meta name="viewport" content="width=device-width, inititial-scale=1.0, user-scalable=no" />
  <%= csrf_meta_tags %>
</head>
<body <% if user_signed_in? %>class="paddingmobile"<% end %> >
	
	<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
	  <!-- Brand and toggle get grouped for better mobile display -->
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	    <a class="navbar-brand" href="<%= root_path %>">EthanBook</a>
		
	  </div>

	  <!-- Collect the nav links, forms, and other content for toggling -->
	  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	    <ul class="nav navbar-nav">
    	      <li class="<%= 'active' if current_page?(root_path) or current_page?(feed_path) or current_page?(statuses_path) %>"><%= link_to "Feed", root_path %></li>

    	      
	          
	        </ul>
	   
	    <form class="navbar-form navbar-left" role="search">
		
	      <div class="form-group">
			  <div class="searchbar">
			 	<input type="text" class="form-control" placeholder="Search for people, places and things">
			   </div>
	      </div>
		  	<button type="submit" class="btn btn-default">Search</button>	
	    </form>
	    <ul class="nav navbar-nav navbar-right">
  	     	<% if user_signed_in? %>
		 
		 		<li><%= link_to current_user.full_name, profile_path(current_user.profile_name) %></li>
  	     		<li><%= link_to "Settings", edit_user_registration_path %></li>
				<li class="rightnav"><%= link_to "Log Out", logout_path %></li>
			<% else %>
				
				<li><%= link_to "Register", register_path %></li>
				<li class="rightnavx2"><%= link_to "Sign In", sign_in_path %></li>
			
	      	<% end %>
	    </ul>
	  </div><!-- /.navbar-collapse -->
	</nav>
	
	<div class="container">
		
		<% flash.each do |type, message| %><br />
			<div class="alert <%= flash_class type %>">
				<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				<%= message %>
			</div>
			
			
		<% end %>
		
		<%= yield %>
	</div>
	
	
</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
	<h1><%= @user.full_name %></h1>
</div>

<% if @statuses %>
	<legend><%= @user.full_name %>'s Statuses</legend>
	<% @statuses.each do |status| %>
	<div class="well">
		<div style="padding-bottom:8px;"><%= status.content %></div>
		<%= link_to time_ago_in_words(status.created_at) + " ago", status_path(status) %> 
		</div>
	<% end %>
<% end %>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, class: "form-horizontal") do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 	  <strong><%= current_user.full_name %></strong>
	
    <div "form">
      <br /><%= f.input :content %>
    </div>

  <div class="form-actions">
	  <br />

    <%= f.button :submit, class: "btn-primary" %>
  </div>
  <br />
<% end %>

app/views/statuses/edit.html.erb
<div class="page-header">
	<h1>Editing status</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back to Feed', root_path %>

app/views/statuses/index.html.erb
<div class="page-header">	
	<h1>Statuses</h1>
</div>
<%= link_to 'Post a new Status', new_status_path, class: "btn btn-default", style: "margin-bottom:20px;" %>

<% @statuses.each do |status| %>
<div class="status"> 
	<div class="row">
		<div class="col-xs-1 pic">
			<%= image_tag status.user.gravatar_url %>
		</div>
		<div class="col-xs-7 moveover">  
			<strong><%= status.user.full_name %></strong>
		    <p width="100%"><%= status.content %></p>
			<div class="meta">
		        <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
				<span class="admin"><% if status.user == current_user %>
		        	| <%= link_to 'Edit', edit_status_path(status) %> | <%= link_to 'Delete', status, :data => { :confirm => "Are you sure?" }, :method => :delete %><% end %>
				</span>
			</div>
		</div>
	</div>
</div>     
<% end %>

app/views/statuses/new.html.erb
<div class="page-header">	
	<h1>New status</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back to Feed', root_path %>

app/views/statuses/show.html.erb
<div class="page-header">
	<h1>Statuses</h1>
</div>

<div class="status"> 
	<div class="row">  
		<div class="col-xs-1 pic">
			<%= image_tag @status.user.gravatar_url %>
		</div>
		<div class="col-xs-7 moveover">
			<strong><%= @status.user.full_name %></strong>
		    <p><%= @status.content %></p>
			<div class="meta">
				<%= link_to 'Back to Feed', root_path %> | 
		        <%= link_to time_ago_in_words(@status.created_at) + " ago", @status %>
				<span class="admin"><% if @status.user == current_user %>
		        	| <%= link_to 'Edit', edit_status_path(@status) %>
		        	<% end %>
				</span>
			</div>
		</div>
	</div>
</div>     